DZ/DZ/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('home/admin/', admin.site.urls),
]
from django.urls import include
from django.urls import path

urlpatterns += [
    path('home/', include('firstapp.urls')),
]

from django.views.generic import RedirectView

urlpatterns += [
    path('', RedirectView.as_view(url='/home/', permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DZ/firstapp/urls.py
from django.urls import path
from numpy.core import generic

from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^DB/$', views.DB.as_view(), name='DB'),
]




DZ/firstapp/models.py
from django.db import models


class PhoneBrand(models.Model):
    Brand = models.CharField(max_length=30)
    Site = models.CharField(max_length=50)
    Subscrprice = models.IntegerField()

    def __str__(self):
        return self.Brand


class Phone(models.Model):
    PhoneBrand = models.ForeignKey(PhoneBrand, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    prise = models.IntegerField()
    description = models.CharField(max_length=150)

    def __str__(self):
        return self.name

DZ/firstapp/views.py
from django.shortcuts import render
from firstapp.models import PhoneBrand, Phone
from django.views import generic

def index(request):
    return render(request, 'index.html', {})


#def DB(request):
    #return render(request, 'DB.html', {})


class DB(generic.ListView):
    model = PhoneBrand
    context_object_name = 'PhoneBrand'
    template_name = 'DB.html'

DZ/firstapp/templates/DB.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Данные из нашей БД</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
{% block content%}
<h1>Phone Brand</h1>
{% if PhoneBrand %}
<ul>
{% for element in PhoneBrand %}
<li>
<a href="#">{{ element.Brand }}</a> ({{element.Site}})
    <ul>{% for elem in element.phone_set.all %}
        <li>
            {{ elem.name }}
            {{ elem.description }}
        </li>
    {% endfor %}
    </ul>
</li>
{% endfor %}
</ul>
{% else %}
<p>Error 404.There are no PhoneBrands.</p>
{% endif %}
{% endblock%}
</body>
</html>

DZ/firstapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Master-Detail Pattern</title>
    <meta name="viewport" content="width=device-width">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
{% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="">
<nav class="navbar navbar-expand-md sticky-top navbar-dark bg-dark">
<div class="container-fluid d-flex justify-content-between xxx">
<div>
<a class="navbar-brand">Домашнее задание по курсу "Разработка интернет приложений"</a>
</div>                                  <
<div class="d-flex justify-content-between" id="navbarNavDropdown">
</div>
<ul class="navbar-nav rr">
<li class="nav-item">
<a class="nav-link active" aria-current="page" href="{% url 'DB' %}">Открытие данных из БД</a>
</li>
<li class="nav-item">
<a class="nav-link active" aria-current="page" href="../../home/admin">Панель администратора</a>
</li>
</ul
</div>
</nav>
        <ul>Домашнее задание</ul>
        <ul>Студента группы ИУ5-51Б</ul>
        <ul>Овчинникова Степана</ul>
</div>
</body>
</html>